#!/bin/bash
#30 = black
#31 = red
#32 = green
#33 = yellow
#34 = blue
#35 = pink
#36 = cyan
#37 = white
export CBLACK="\e[0;30m"
export CRED="\e[0;31m"
export CGREEN="\e[0;32m"
export CYELLOW="\e[0;33m"
export CBLUE="\e[0;34m"
export CPINK="\e[0;35m"
export CCYAN="\e[0;36m"
export CWHITE="\e[0;37m"
export CDEFAULT="\e[0m"

if [ "$USER" = "root" ]; then
	CUSER="${CRED}"
else
	CUSER="${CGREEN}"
fi