#!/bin/bash
#30 = black
#31 = red
#32 = green
#33 = yellow
#34 = blue
#35 = pink
#36 = cyan
#37 = white

if [ -n "$BASH_VERSION" ]; then
  CBLACK="\033[0;30m"
  CRED="\033[0;31m"
  CGREEN="\033[0;32m"
  CYELLOW="\033[0;33m"
  CBLUE="\033[0;34m"
  CPINK="\033[0;35m"
  CCYAN="\033[0;36m"
  CWHITE="\033[0;37m"
  CDEFAULT="\033[0m"

  PBLACK="\001\033[0;30m\002"
  PRED="\001\033[0;31m\002"
  PGREEN="\001\033[0;32m\002"
  PYELLOW="\001\033[0;33m\002"
  PBLUE="\001\033[0;34m\002"
  PPINK="\001\033[0;35m\002"
  PCYAN="\001\033[0;36m\002"
  PWHITE="\001\033[0;37m\002"
  PDEFAULT="\001\033[0m\002"
elif [ -n "$ZSH_VERSION" ]; then
  autoload -U colors && colors
  CBLACK="$fg[black]"
  CRED="$fg[red]"
  CGREEN="$fg[green]"
  CYELLOW="$fg[yellow]"
  CBLUE="$fg[blue]"
  CPINK="$fg[magenta]"
  CCYAN="$fg[cyan]"
  CWHITE="$fg[white]"
  CDEFAULT="$reset_color"
fi

if [[ "$USER" = "root" ]]; then
  CUSER="${CRED}"
else
  CUSER="${CGREEN}"
fi

