#!/bin/bash
if [ -n "$BASH_VERSION" ]; then
  export HISTFILESIZE=1000000
  export HISTSIZE=1000000
  export HISTTIMEFORMAT='%F %T '
  export HISTFILE="$HOME/.full_bash_history"
  assert_in_prompt_command 'history -a'
fi
