#!/bin/bash

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
echo "bashrc repo found at $SCRIPTDIR"

if [ -d /etc/bashrc.extensions ]; then
  rm -rf /etc/bashrc.extensions
fi
cp -r "$SCRIPTDIR/" /etc/bashrc.extensions/

if [ -d /etc/profile.d/ ]; then
  echo "Updating /etc/profile.d/bashrc.extensions.sh"
  echo "source /etc/bashrc.extensions/main" > /etc/profile.d/bashrc.extensions.sh
  chmod 755 /etc/profile.d/bashrc.extensions.sh
else
  if [ -f /etc/bashrc ]; then
    echo "source /etc/bashrc.extensions/main" >> /etc/bashrc
  elif [ -f /etc/bash.bashrc ]; then
    echo "source /etc/bashrc.extensions/main" >> /etc/bash.bashrc
  fi
  if [ -f /root/.bashrc ]; then
    # If the common bashrc is not sourced
    if ! grep -q ' /etc/bashrc' /root/.bashrc; then
      echo "source /etc/bashrc.extensions/main" >> /root/.bashrc
    fi
  fi
  if [ -d /private/var/root/ ]; then
    # OSX specific install
    echo "source /etc/bashrc.extensions/main" >> /private/var/root/.bashrc
    chsh -s /bin/bash
  fi
fi

if ! [ -d "$HOME/profile.d" ]; then
  rsync -av "$SCRIPTDIR/profile.d/" "$HOME/profile.d/"
fi

echo '
The maludwig/bashrc extensions were installed to /etc/bashrc.extensions
  You can delete this directory now, if you like.
  If you want to extend the current set with your own user-specific extensions
   you can add them to your local ~/profile.d with a .sh extension
  Check out ~/profile.d/sample.sh for an example.
  On most platforms /etc/profile.d/*.sh scripts are run for all users.

Restart bash to experience the new world
'

