#!/bin/bash
mkdir /etc/bashrc.extensions
cp -r ./ /etc/bashrc.extensions/
if [ -f /etc/bashrc ]; then
  echo "source /etc/bashrc.extensions/main" >> /etc/bashrc
elif [ -f /etc/bash.bashrc ]; then
  echo "source /etc/bashrc.extensions/main" >> /etc/bash.bashrc
fi
echo "source /etc/bashrc.extensions/main" >> /private/var/root/.bashrc
echo "source /etc/bashrc.extensions/main" >> /private/var/root/.bashrc
chsh -s /bin/bash

